### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [8]:
import numpy as np

arra1 = np.random.randint(1, 20, size=(5, 5))
arra1[:,2]=1
arra1


array([[14, 18,  1,  2, 11],
       [15, 16,  1, 18, 19],
       [ 8, 19,  1,  5,  5],
       [19,  8,  1, 10, 14],
       [17, 18,  1, 12,  6]], dtype=int32)

In [10]:
arra2 = np.random.randint(1, 16, size=(4, 4))
np.fill_diagonal(arra2, 0)
arra2

array([[ 0,  2,  7, 15],
       [ 2,  0,  1,  3],
       [ 4,  7,  0, 15],
       [ 8, 12, 12,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [11]:
arra1 = np.arange(1,37).reshape(6,6)
sub_Array = arra1[2:5, 1:4]
sub_Array

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [21]:
arra2 = np.random.randint(1, 10, size=(5, 5))
border_elements = np.zeros_like(arra2)
print(border_elements)
print(arra2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[3 9 5 6 4]
 [5 6 7 9 2]
 [6 6 4 1 1]
 [2 5 9 4 8]
 [3 8 2 5 7]]


In [25]:
border_elements[0, :] = arra2[0, :]
border_elements[-1,:] = arra2[-1,:]
border_elements[:,0] = arra2[:,0]
border_elements[:,-1] = arra2[:,-1]
border_elements

array([[3, 9, 5, 6, 4],
       [5, 0, 0, 0, 2],
       [6, 0, 0, 0, 1],
       [2, 0, 0, 0, 8],
       [3, 8, 2, 5, 7]], dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [29]:
arr1 = np.random.randint(1, 10, size=(3, 4))
arra2 = np.random.randint(1, 10, size=(3, 4))
result = arr1 + arra2
result
result = arr1 - arra2
result
result = arr1 * arra2
result
result = arr1 / arra2
result

array([[0.6       , 0.66666667, 0.75      , 0.75      ],
       [1.        , 1.125     , 0.5       , 4.        ],
       [2.33333333, 0.85714286, 4.        , 0.6       ]])

In [37]:
arr3 = np.random.randint(1, 16, size=(4, 4))
row_sum = arr3.sum(axis=1)
row_sum

array([33, 25, 12, 22])

In [38]:
column_sum = arr3.sum(axis=0)
column_sum


array([23, 14, 24, 31])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [44]:
array = np.random.randint(1, 101, size=(5, 5))
mean= np.mean(array)
mean_value = np.mean(array)
median_value = np.median(array)
std_dev = np.std(array)
variance = np.var(array)
mean, mean_value, median_value, std_dev, variance


(np.float64(42.32),
 np.float64(42.32),
 np.float64(38.0),
 np.float64(28.78015983277369),
 np.float64(828.2976000000001))

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [59]:
arraya=np.random.randint(1, 10, size=(4, 4))
arrayb=arraya[0:1,:]
arrayb,arraya

(array([[4, 2, 6, 8]], dtype=int32),
 array([[4, 2, 6, 8],
        [4, 9, 8, 4],
        [6, 9, 7, 8],
        [5, 9, 1, 3]], dtype=int32))

In [ ]:
array_2d = np.random.randint(1, 51, size=(3, 3))
array_1d = np.random.randint(1, 51, size=(3,))
result_array_column = np.column_stack((array_2d, array_1d))
result_array_column



array([[27, 18, 35,  1],
       [29,  5, 27, 38],
       [18, 30, 34,  6]], dtype=int32)

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [60]:
matrix = np.random.randint(1, 11, size=(3, 3))
determinant = np.linalg.det(matrix)
try:
    inverse = np.linalg.inv(matrix)
except np.linalg.LinAlgError:
    inverse = "La matriz no es invertible"
determinant, inverse

(np.float64(149.99999999999997),
 array([[-0.04      ,  0.14      , -0.06      ],
        [-0.02666667, -0.07333333,  0.46      ],
        [ 0.16      , -0.06      , -0.26      ]]))

In [61]:
eigenvalues = np.linalg.eigvals(matrix)
eigenvalues

array([15.30068778+0.j        , -2.15034389+2.27585194j,
       -2.15034389-2.27585194j])

In [62]:
matrix_A = np.random.randint(1, 10, size=(2, 3))
matrix_B = np.random.randint(1, 10, size=(3, 2))
matrix_product = np.dot(matrix_A, matrix_B)
matrix_product

array([[35, 51],
       [52, 68]], dtype=int32)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [74]:
array1 = np.arange(1, 10).reshape(3,3)
array1x9 = array1.reshape(1,9)
array9x1 = array1.reshape(9,1)

array1, array1x9, array9x1

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [ ]:

array_5x5 = np.random.randint(1, 51, size=(5, 5))
print(array_5x5)

corner_elements = array_5x5[[0, 0, -1, -1], [0, -1, 0, -1]]

print(corner_elements)
array_4x4 = np.random.randint(1, 21, size=(4, 4))

print(array_4x4)
array_4x4[array_4x4 > 10] = 10



[[ 7  3 28 30 33]
 [15 32 27  6 19]
 [47 37  8 37  5]
 [ 9 12 30 42 27]
 [11 19 18 37 30]]
[ 7 33 11 30]
[[15  7  8 12]
 [10 15  4 16]
 [ 6  7  6 11]
 [ 6 14  2  1]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [80]:

structured_array = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 75.2),
    ('Charlie', 22, 68.9),
    ('David', 35, 80.0)
], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])


sorted_array = np.sort(structured_array, order='age')


points = np.array([
    (1, 2),
    (4, 6),
    (7, 8),
    (2, 3)
], dtype=[('x', 'i4'), ('y', 'i4')])


num_points = len(points)
distances = np.zeros((num_points, num_points))

for i in range(num_points):
    for j in range(num_points):
        distances[i, j] = np.sqrt((points[i]['x'] - points[j]['x'])**2 + (points[i]['y'] - points[j]['y'])**2)

distances


array([[0.        , 5.        , 8.48528137, 1.41421356],
       [5.        , 0.        , 3.60555128, 3.60555128],
       [8.48528137, 3.60555128, 0.        , 7.07106781],
       [1.41421356, 3.60555128, 7.07106781, 0.        ]])

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [82]:
import numpy.ma as ma
array_4x4 = np.random.randint(1, 21, size=(4, 4))
masked_array_4x4 = ma.masked_greater(array_4x4, 10)
masked_array_4x4

masked_array(
  data=[[5, --, --, 7],
        [10, --, --, --],
        [--, --, 8, --],
        [1, 7, 2, 10]],
  mask=[[False,  True,  True, False],
        [False,  True,  True,  True],
        [ True,  True, False,  True],
        [False, False, False, False]],
  fill_value=np.int64(999999),
  dtype=int32)

In [84]:
sum_unmasked = masked_array_4x4.sum()
sum_unmasked

np.int64(50)

In [85]:
array_3x3 = np.random.randint(1, 21, size=(3, 3))
print(array_3x3)
masked_array_3x3 = ma.masked_array(array_3x3, mask=np.eye(3, dtype=bool))
masked_array_3x3

[[12  4 19]
 [ 9 19  6]
 [ 4 20 18]]


masked_array(
  data=[[--, 4, 19],
        [9, --, 6],
        [4, 20, --]],
  mask=[[ True, False, False],
        [False,  True, False],
        [False, False,  True]],
  fill_value=np.int64(999999),
  dtype=int32)

In [88]:
mean_unmasked = masked_array_3x3.mean()
mean_unmasked



np.float64(10.333333333333334)

In [89]:
masked_array_3x3 = masked_array_3x3.filled(mean_unmasked)
masked_array_3x3

array([[10,  4, 19],
       [ 9, 10,  6],
       [ 4, 20, 10]], dtype=int32)